import "../styles/globals.css";

export const metadata = {
  title: "Sanity Blogg",
  description: "Generated by Rikard",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>{children}</body>
    </html>
  );
}
